<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Notification.Application\Notification.Application.csproj" />
    <ProjectReference Include="..\Notification.Domain\Notification.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="3.1.0" />
    <PackageReference Include="WebPush" Version="1.0.13" />
  </ItemGroup>
</Project>
