using MongoDB.Bson.Serialization.Attributes;

namespace Notification.Domain.Documents;

public enum NotificationType
{
    Message = 0,
    Mention = 1,
    Reply = 2,
    Moderation = 3,
    System = 4
}

/// <summary>
/// Collection "notifications".
///
/// The message text is generated by the producing service and only ever contains an
/// anonymous name — never a real identity. Notifications used to be readable by
/// anyone, which disclosed who was messaging whom.
/// </summary>
public sealed class NotificationDocument
{
    [BsonId]
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>The recipient. Every query is scoped by this and the caller's token.</summary>
    public Guid UserId { get; set; }

    public string Title { get; set; } = string.Empty;
    public string Message { get; set; } = string.Empty;

    public NotificationType Type { get; set; } = NotificationType.Message;

    public bool IsRead { get; set; }
    public DateTime? ReadAt { get; set; }

    /// <summary>
    /// The message or entity that produced this. Lets a notification be withdrawn when
    /// its source is deleted.
    /// </summary>
    public Guid? SourceId { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}

/// <summary>
/// Collection "pushSubscriptions". Unique on the endpoint, because a browser reports
/// the same endpoint for the same installation.
/// </summary>
public sealed class PushSubscriptionDocument
{
    [BsonId]
    public Guid Id { get; set; } = Guid.NewGuid();

    public Guid UserId { get; set; }

    public string Endpoint { get; set; } = string.Empty;
    public string P256dh { get; set; } = string.Empty;
    public string Auth { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime LastUsedAt { get; set; } = DateTime.UtcNow;

    /// <summary>Consecutive delivery failures. Used to retire a dead endpoint.</summary>
    public int FailureCount { get; set; }
}
